### ISSUE TITLE
store upvotes(store each with timestamp, so that we can show very detailed stats)

### ISSUE THREAD

**Issue by johnrushx** [MarsX-dev/devhunt#6]
also in supabase.
make sure it's protected from fake upvoted. Every user can only make one. Even if they hack and do it via api, check on the server to make sure one user = 1 upvote.
Store everything you can
- IP
- agent
- time
- user
- country
- ...

**Comment by NadaaFarook** [comment]
I'd like to take up this task

**Comment by vitalikmay** [comment]
@johnrushx & @NadaaFarook I don't think that it makes sense to do it in such sophisticated way. Since only registered users can vote, there is a simple way to control it. You can look at my supabase function called `upvoteComment` (it's not tested yet but you will understand the concept) and the "Comments" service #22 - if you use `userId` and `productId` as a unique primary key and extract `userId` from session then there is no way to put more than 1 vote per product/tool. It's more than enough to prevent fake upvotes.
